Fecha: 16/04/2025
Autor: Gustavo V. Diaz
Finalmente implementé SNAP 11 en contenedor e hice los cambios pertinentes para que funcione con el paquete snappy 11 y python 3.10.

Ahora regitro una respuesta del procesador cuando no le alcanza el tiempo para recibir la respuesta del servidor de la ESA. Lo dejo para atajar este error.

Registro 

/dev/pts/1                                                                                                                                                              A continuación se requerirá el ingreso del usuario de dataspace copernicus:                                                                                             Ingreso de usuario: gus838@gmail.com                                                                                                                                    Ingreso de contraseña (para gus838@gmail.com):                                                                                                                          Credenciales inválidas, vuelva a ingresarlas por favor.                                                                                                                 A continuación se requerirá el ingreso del usuario de dataspace copernicus:                                                                                             Ingreso de usuario: gus838@gmail.com                                                                                                                                    Ingreso de contraseña (para gus838@gmail.com):                                                                                                                          Credenciales validas                                                                                                                                                    Collection/Name eq 'SENTINEL-2' and contains(Name,'MSIL2A')                                                                                                             MULTIPOLYGON (((-58.7757763092653 -35.4702267217582,-58.7802506263501 -35.4733463110006,-58.7775145331687 -35.4758890799229,-58.7730402160839 -35.4727695893355,-58.7757763092653 -35.4702267217582)))                                                                                                                                          gt 2023-01-01T00:00:00.000Z                                                                                                                                             lt 2024-03-01T00:00:00.000Z                                                                                                                                             ContentDate/Start                                                                                                                                                       1000                                                                                                                                                                    https://catalogue.dataspace.copernicus.eu/odata/v1/Products?$filter=Collection/Name eq 'SENTINEL-2' and contains(Name,'MSIL2A') and OData.CSC.Intersects(area=geography'SRID=4326;MULTIPOLYGON (((-58.7757763092653 -35.4702267217582,-58.7802506263501 -35.4733463110006,-58.7775145331687 -35.4758890799229,-58.7730402160839 -35.4727695893355,-58.7757763092653 -35.4702267217582)))') and Attributes/OData.CSC.DoubleAttribute/any(att:att/Name eq 'cloudCover' and att/OData.CSC.DoubleAttribute/Value le 100) and ContentDate/Start gt 2023-01-01T00:00:00.000Z and ContentDate/Start lt 2024-03-01T00:00:00.000Z&$orderby=ContentDate/Start&$top=1000&$expand=Attributes                Traceback (most recent call last):                                                                                                                                        File "/src/Scripts/searcher_filter.py", line 24, in <module>                                                                                                              df = msf.req_to_df(json['value'])                                                                                                                                   KeyError: 'value'                                                                                                                                                       ++ cd ../                                                                                                                                                               ++ cd ../                                                                                                                                                               ++ pwd                                                                                                                                                                  + PATH_REPO=/home/negrete/Documentos/NDVI_S2_gauge                                                                                                                      + PATH_SCRIPTS=/home/negrete/Documentos/NDVI_S2_gauge/Scripts                                                                                                           + PATH_VECTORES=/home/negrete/Documentos/NDVI_S2_gauge/Vectores                                                                                                         + PATH_UTILS=/home/negrete/Documentos/NDVI_S2_gauge/utils                                                                                                               + PATH_TOKEN=/home/negrete/Documentos/NDVI_S2_gauge/token                                                                                                               + PATH_OUTPUT=/home/negrete/Documentos/NDVI_S2_gauge/output                                                                                                             + sudo docker run --rm --name snappy_11_develop -v /home/negrete/Documentos/NDVI_S2_gauge/Scripts:/src/Scripts -v /home/negrete/Documentos/NDVI_S2_gauge/Vectores:/src/Vectores -v /home/negrete/Documentos/NDVI_S2_gauge/utils:/src/utils -v /home/negrete/Documentos/NDVI_S2_gauge/token:/src/token -v /home/negrete/Documentos/NDVI_S2_gauge/output:/src/Output --workdir /src/Scripts snappy_11_gvd python3 folder_creator.py                                                                                       Traceback (most recent call last):                                                                                                                                        File "/src/Scripts/folder_creator.py", line 29, in <module>                                                                                                               conf_dict = mfc.read_conf_proc(config_path, verbose2conf)                                                                                                             File "/src/Scripts/../utils/mod_s_snappy_p3_10.py", line 38, in read_conf_proc                                                                                            with open(path2conf,"r") as file:                                                                                                                                   FileNotFoundError: [Errno 2] No such file or directory: '/src/utils/CONF_PROC.INI'                                                                                      Primera impresión                                                                                                                                                                                                                                                                                                                               cat: /home/negrete/Documentos/NDVI_S2_gauge/output/: Es un directorio                                                                                                   ./Proc_one_by_one_snap11.sh: línea 66: read: error de lectura: 0: Es un directorio                                                                                      ++ cd ../                                                                                                                                                               ++ cd ../                                                                                                                                                               ++ pwd                                                                                                                                                                  + PATH_REPO=/home/negrete/Documentos/NDVI_S2_gauge                                                                                                                      + PATH_SCRIPTS=/home/negrete/Documentos/NDVI_S2_gauge/Scripts                                                                                                           + PATH_VECTORES=/home/negrete/Documentos/NDVI_S2_gauge/Vectores                                                                                                         + PATH_UTILS=/home/negrete/Documentos/NDVI_S2_gauge/utils                                                                                                               + PATH_TOKEN=/home/negrete/Documentos/NDVI_S2_gauge/token                                                                                                               + PATH_OUTPUT=/home/negrete/Documentos/NDVI_S2_gauge/output                                                                                                             + sudo docker run --rm --name snappy_11_develop -v /home/negrete/Documentos/NDVI_S2_gauge/Scripts:/src/Scripts -v /home/negrete/Documentos/NDVI_S2_gauge/Vectores:/src/Vectores -v /home/negrete/Documentos/NDVI_S2_gauge/utils:/src/utils -v /home/negrete/Documentos/NDVI_S2_gauge/token:/src/token -v /home/negrete/Documentos/NDVI_S2_gauge/output:/src/Output --workdir /src/Scripts snappy_11_gvd python3 resumer.py                                                                                              Traceback (most recent call last):                                                                                                                                        File "/src/Scripts/resumer.py", line 27, in <module>                                                                                                                      conf_dict = mfc.read_conf_proc(config_path, verbose2conf)                                                                                                             File "/src/Scripts/../utils/mod_s_snappy_p3_10.py", line 38, in read_conf_proc                                                                                            with open(path2conf,"r") as file:                                                                                                                                   FileNotFoundError: [Errno 2] No such file or directory: '/src/utils/CONF_PROC.INI'

*****************************************************************************************************

Fecha: 08/04/2025
Autor: Gustavo V. Diaz
Ejecuté la "acción a tomar 1" de la entrada del 05/04/2025. Y cuando ejecuté el procesador con esa configuración me percaté del problema fix_1. Es decir que con esta versión de snap instalada (snap 9) no puedo abrir productos Sentinel-2 procesados posterior del 01-07-2024.

Esto se tornó un problema importante para resolver asi que antes de continuar con las mejoras debo resolver este tema. En el archivo fix_1.txt doy mayor detalle de los caminos a tomar.

*****************************************************************************************************

Fecha: 05/04/2025
Autor: Gustavo V. Diaz
Registro de archivos que fallaron en la prueba del procesamiento "SMM_vacas_2025_test_3_20250405T033933"
S2A_MSIL2A_20250112T134701_N0511_R024_T21HUA_20250112T183356.SAFE.zip
S2B_MSIL2A_20241208T134709_N0511_R024_T21HUA_20241208T190915.SAFE.zip
S2C_MSIL2A_20250201T134731_N0511_R024_T21HUA_20250201T172610.SAFE.zip
S2A_MSIL2A_20241113T134701_N0511_R024_T21HUA_20241113T183442.SAFE.zip
S2A_MSIL2A_20240924T134711_N0511_R024_T21HUA_20240924T190249.SAFE.zip
S2A_MSIL2A_20240726T134711_N0511_R024_T21HUA_20240727T091206.SAFE.zip

Pendientes:
Probar los últimos productos con una nueva versión del procesador.

* La nueva nueva versión del procesador tendrá el ploteo de histograma junto al producto satelital, también puedo agregar las bandas involucradas en el cómputo del NDVI
* Modificar el registro del producto satelital en RGB para que agregue los valores estadísticos y los histogramas de los mismos.
** La versión del histograma estaría bueno que genere el histograma con las tres bandas

Objetivo:
Comparar los valores medios del imshow y del histograma para ver si tiene sentido lo que veo.

Acciones a tomar:
1_ Configurar CONF_SEARCHER.INI para que baje los productos que reporté y se compute el NDVI
    Fecha inicio: 26-07-2024
    Fecha fin: 12-01-2025 (Agrego un día para que tome el último producto que encontró)
    Vector: Sigo procesando con el vector de SMM
2_ Modificar la función "plotNDVI_s2_png" en el módulo "mod_snappy_S2.py" para que:
    * Genere el histograma del NDVI, B4 y B8 en un solo plot e imprimir mean y std_dev sobre el histograma
    * Plotear el imshow del lado izquierdo y el histograma del lado derecho
3_ Modificar la función "plotRGB_s2_png" en el módulo "mod_snappy_S2.py" para que:
    * Genere el histograma del B2, B3, B4 en un solo plot e imprimir mean y std_dev sobre el histograma
    * Plotear el imshow RGB del lado izquierdo y el histograma del lado derecho
4_ Ejecutar el proceso

*****************************************************************************************************
Archivo para registrar problemas en uso de repositorios

Problema 1 22/08/2023

El día de ayer terminé la jornada generando modificaciones en los notebooks para que funcionen correctamente en pc de casa a través de ssh en la misma pc.

Luego agregué modificaciones en el archivo README.md en el cual registraba dichos cambios.

El día de hoy modifiqué a través de la pc de casa el archivo .gitignore sin haber hecho un pull antes.

Conclusión, hay conflicto entre el repo local de la pc de casa y el repo remoto. Este archivo intentará dejar registro de dicho conflicto.

Solución:

Crear nueva rama iss1 y luego "mergear" ambas ramas con sus archivos modificados.
